name: Blockchain

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest]
        steps:
            - name: Set up Go v1.17
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17
              id: go
            - name: Checkout Repository
              uses: actions/checkout@v3
