name: Lint

on:
    - push
    - pull_request

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: hashicorp/setup-terraform@v1
            - run: terraform fmt -check
